name: ribasim

channels:
  - conda-forge
    
dependencies:
  - python >= 3.9
  - matplotlib
  - pandas
  - geopandas
  - pandera
  - pyarrow
  - pydantic
  - pyogrio
  - shapely >=2.0
  - tomli
  - tomli-w
  - xarray
