
# [s] Î”t for periodic update frequency, including user horizons
update_timestep = 86400.0
# path to the UGrid NetCDF with the network, profiles, user and forcing data
input_path = "data/ugrid/input-mozart.nc"
lsw_ids = [151358, 151371, 151309]

# dw_hupsel = 24  # Berkel / Slinge
# dw_tol = 42  # around Tol
# TODO support this as an override of lsw_ids
dw_id = 24
