project:
  type: website

website:
  title: "Bach"
  navbar:
    left:
      - equations.qmd
      - modflow.qmd
      - demo.ipynb
      - coupling-demo.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

bibliography: references.bib
juypter: julia-1.8
number-sections: true
