profile:
  group:
    - [website, manual]

quartodoc:
  style: pkgdown
  dir: python/reference
  title: API Reference
  package: ribasim
  sections:
    - title: Model
      desc: The Model class represents an entire Ribasim model.
      contents:
        - Model
    - title: Edge
      desc: The Edge database layer.
      contents:
        - EdgeTable
    - title: Node types
      desc: Available node types to model different situations.
      contents:
        - nodes.basin
        - nodes.fractional_flow
        - nodes.tabulated_rating_curve
        - nodes.pump
        - nodes.outlet
        - nodes.user_demand
        - nodes.level_boundary
        - nodes.flow_boundary
        - nodes.linear_resistance
        - nodes.manning_resistance
        - nodes.terminal
        - nodes.discrete_control
        - nodes.pid_control
        - nodes.flow_demand
        - nodes.level_demand
