[modflow6]
simulation = "../data/hupsel-steady-state/mfsim.nam"
mode = "sequential"

[modflow6.models]
[modflow6.models.gwf]
    type = "gwf"
    dataset = "../data/volume_level_profile-hupsel.nc"
    basins = "lwd_id"
    
    [[modflow6.models.gwf.bounds]]
    river = "RIV_P"
    drain = "DNR_P"
    profile = "profile_primary"

    [[modflow6.models.gwf.bounds]]
    river = "RIV_S"
    drain = "DNR_S"
    profile = "profile_secondary"

    [[modflow6.models.gwf.bounds]]
    drain = "DNR_T"
    profile = "profile_tertiary"
