[modflow6]
simulation = "../data/hupsel-steady-state/mfsim.nam"
mode = "sequential"

[modflow6.models]
[modflow6.models.gwf]
    type = "gwf"
    dataset = "c:/src/bach/data/volume_level_profile-hupsel.nc"
    basins = "lsw_id"
    
    [[modflow6.models.gwf.bounds]]
    river = "RIV_P"
    drain = "DRN_P"
    profile = "profile_primary"

    [[modflow6.models.gwf.bounds]]
    river = "RIV_S"
    drain = "DRN_S"
    profile = "profile_secondary"

    [[modflow6.models.gwf.bounds]]
    drain = "DRN_T"
    profile = "profile_tertiary"
